Web/Controllers/BookingsArchiveController.cs
using DDPS.Api;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace DDPS.Web.Controllers
{
    [Authorize(Roles = "admin, manager")]
    public class BookingsArchiveController : Controller
    {

        private readonly HotelContext _context;

        public BookingsArchiveController(HotelContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var context = _context.BookingsArchive;

            return View(await context.ToListAsync());
        }
    }
}

Web/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DDPS.Api;
using DDPS.Api.Entities;
using DDPS.Api.TempModels;
using Microsoft.AspNetCore.Identity;
using DDPS.Web.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using OfficeOpenXml;

namespace DDPS.Web.Controllers
{
    [Authorize(Roles = "admin, manager, client")]
    public class ClientsController : Controller
    {
        private readonly HotelContext _context;
        private readonly UserManager<DDPSUser> _userManager;
        private readonly IWebHostEnvironment _appEnvironment;

        public ClientsController(HotelContext context, UserManager<DDPSUser> userManager, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }


        // GET: Clients
        public async Task<IActionResult> Index()
        {
            TempData.Clear();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (await _userManager.IsInRoleAsync(user, "admin") || await _userManager.IsInRoleAsync(user, "manager"))
            {
                return _context.Clients != null ?
                              View(await _context.Clients.ToListAsync()) :
                              Problem("Entity set 'HotelContext.Clients'  is null.");
            }
            else
            {
                return View(await _context.Clients.Where(c => c.Email == user.Email).ToListAsync());
            }

        }
        [Authorize(Roles = "admin, manager, client")]
        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var clients = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clients == null)
            {
                return NotFound();
            }

            ClientDetailsModel clientDetailsModel = new()
            {
                Client = clients,
                Bookings = _context.Bookings.Where(c => c.ClientId == id && c.IsActive).ToList(),
            };

            return View(clientDetailsModel);
        }

        [Authorize(Roles = "admin, manager")]
        // GET: Clients/Create
        public IActionResult Create(bool? FromNewBooking)
        {
            if(FromNewBooking.HasValue && FromNewBooking.Value is true)
            {
                TempData["FromNewBookingToClients"] = FromNewBooking.Value;
            }
            return View();
        }

        [Authorize(Roles = "admin, manager")]
        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SecondName,FirstName,LastName,Email,PhoneNumber")] Clients clients)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clients);
                await _context.SaveChangesAsync();
                if ((bool?)TempData["FromNewBookingToClients"] == true)
                {
                    return RedirectToAction("FirstStepClient", "NewBooking");
                }
                
                return RedirectToAction(nameof(Index));
            }
            return View(clients);
        }

        [Authorize(Roles = "admin, manager")]
        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var clients = await _context.Clients.FindAsync(id);
            if (clients == null)
            {
                return NotFound();
            }
            return View(clients);
        }

        [Authorize(Roles = "admin, manager")]
        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SecondName,FirstName,LastName,Email,PhoneNumber")] Clients clients)
        {
            if (id != clients.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clients);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientsExists(clients.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clients);
        }

        [Authorize(Roles = "admin")]
        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var clients = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clients == null)
            {
                return NotFound();
            }

            return View(clients);
        }

        [Authorize(Roles = "admin")]
        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clients == null)
            {
                return Problem("Entity set 'HotelContext.Clients'  is null.");
            }
            var clients = await _context.Clients.FindAsync(id);
            if (clients != null)
            {
                foreach(var booking in _context.Bookings.Where(b => b.Client.Id == clients.Id).ToList())
                {
                    _context.Bookings.Remove(booking);
                }
                _context.Clients.Remove(clients);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<FileResult> GetBookingsForCurrentClient(int? id)
        {
            // Путь к файлу с шаблоном
            string path = "/Reports/OrdersForCurrentClientTemplate.xlsx";
            //Путь к файлу с результатом
            string result = "/Reports/OrdersForCurrentClient.xlsx";
            FileInfo fi = new FileInfo(_appEnvironment.WebRootPath + path);
            FileInfo fr = new FileInfo(_appEnvironment.WebRootPath + result);
            //будем использовть библитотеку не для коммерческого использования
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            //открываем файл с шаблоном

            var client = await _context.Clients.FirstOrDefaultAsync(m => m.Id == id);

            using (ExcelPackage excelPackage = new ExcelPackage(fi))
            {
                //устанавливаем поля документа
                excelPackage.Workbook.Properties.Author = "Андронов И.А.";
                excelPackage.Workbook.Properties.Title = $"Список всех заказов клиента {client.SecondName} {client.FirstName} {client.LastName}";
                excelPackage.Workbook.Properties.Subject = $"Заказы клиента {client.SecondName} {client.FirstName} {client.LastName}";
                excelPackage.Workbook.Properties.Created = DateTime.Now;
                //плучаем лист по имени.
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets["ClientsOrders"];
                //получаем списко пользователей и в цикле заполняем лист данными
                int startLine = 2;

                var bookings = _context.Bookings.Where(c => c.ClientId == id && c.IsActive)
                    .Include(a => a.Apartament).ThenInclude(f => f.Facilities)
                    .Include(a => a.Apartament).ThenInclude(s => s.Services)
                    .Include(c => c.Client)
                    .Include(s => s.Services).ToList();

                foreach (var booking in bookings)
                {
                    worksheet.Cells[startLine, 1].Value = booking.Apartament.Number;
                    worksheet.Cells[startLine, 2].Value = booking.Apartament.Tariff.Name;
                    worksheet.Cells[startLine, 3].Value = booking.StartTime.ToString("dd-MM-yyyy");
                    worksheet.Cells[startLine, 4].Value = booking.EndTime.ToString("dd-MM-yyyy");
                    worksheet.Cells[startLine, 5].Value = String.Join(Environment.NewLine, booking.Services.Select(s => s.Name));
                    worksheet.Cells[startLine, 6].Value = String.Join(Environment.NewLine, booking.Apartament.Services.Select(s => s.Name));
                    worksheet.Cells[startLine, 7].Value = (booking.Services.Sum(s => s.Price) + (booking.EndTime - booking.StartTime).Days * (booking.Apartament.Tariff.Price + (booking.Apartament.Area * 50) + (int)(0.5 * booking.Apartament.Services.Sum(s => s.Price))));

                    startLine++;
                }
                //созраняем в новое место
                excelPackage.SaveAs(fr);
            }
            // Тип файла - content-type
            string file_type = "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet";
            // Имя файла - необязательно
            string file_name = $"{client.SecondName} {client.FirstName[0]}. {client.LastName[0]}. Bookings.xlsx";
            

Web/Controllers/TariffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DDPS.Api;
using DDPS.Api.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace DDPS.Web.Controllers
{
    [Authorize(Roles = "admin, manager, client")]
    public class TariffsController : Controller
    {
        private readonly HotelContext _context;

        public TariffsController(HotelContext context)
        {
            _context = context;
        }

        // GET: Tariffs
        public async Task<IActionResult> Index()
        {
            TempData.Clear();

            return _context.Tariffs != null ? 
                          View(await _context.Tariffs.ToListAsync()) :
                          Problem("Entity set 'HotelContext.Tariffs'  is null.");
        }

        [Authorize(Roles = "admin, manager, client")]
        // GET: Tariffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tariffs == null)
            {
                return NotFound();
            }

            var tariffs = await _context.Tariffs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tariffs == null)
            {
                return NotFound();
            }

            return View(tariffs);
        }

        [Authorize(Roles = "admin")]
        // GET: Tariffs/Create
        public IActionResult Create(bool? FromNewBooking, bool? FromNewApartament)
        {
            if (FromNewBooking.HasValue && FromNewBooking.Value is true)
            {
                TempData["FromNewBookingToTariffs"] = FromNewBooking.Value;
            }

            if (FromNewApartament.HasValue && FromNewApartament.Value is true)
            {
                TempData["FromNewApartamentToTariffs"] = FromNewApartament.Value;
            }
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Tariffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price")] Tariffs tariffs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tariffs);
                await _context.SaveChangesAsync();
                if ((bool?)TempData["FromNewBookingToTariffs"] == true)
                {
                    return RedirectToAction("ThirdStepTariff", "NewBooking");
                }
                if ((bool?)TempData["FromNewApartamentToTariffs"] == true)
                {
                    return RedirectToAction("SecondStepTariff", "NewApartament");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tariffs);
        }

        [Authorize(Roles = "admin")]
        // GET: Tariffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tariffs == null)
            {
                return NotFound();
            }

            var tariffs = await _context.Tariffs.FindAsync(id);
            if (tariffs == null)
            {
                return NotFound();
            }
            return View(tariffs);
        }

        [Authorize(Roles = "admin")]
        // POST: Tariffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price")] Tariffs tariffs)
        {
            if (id != tariffs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tariffs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TariffsExists(tariffs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tariffs);
        }

        [Authorize(Roles = "admin")]
        // GET: Tariffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tariffs == null)
            {
                return NotFound();
            }

            var tariffs = await _context.Tariffs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tariffs == null)
            {
                return NotFound();
            }

            return View(tariffs);
        }

        [Authorize(Roles = "admin")]
        // POST: Tariffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tariffs == null)
            {
                return Problem("Entity set 'HotelContext.Tariffs'  is null.");
            }
            var tariffs = await _context.Tariffs.FindAsync(id);
            
            if (tariffs != null)
            {
                _context.Apartaments.RemoveRange(_context.Apartaments.Where(a => a.TariffId == tariffs.Id));
                _context.Tariffs.Remove(tariffs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TariffsExists(int id)
        {
          return (_context.Tariffs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>АРМ администратора гостиницы</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">АРМ администратора гостиницы</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Apartaments" asp-action="Index">Апартаменты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Bookings" asp-action="Index">Бронирования</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Clients" asp-action="Index">Клиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Facilities" asp-action="Index">Удобства</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Tariffs" asp-action="Index">Тарифы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="BookingsArchive" asp-action="Index">Архив бронирований</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>
</main>

@*<footer class="border-top footer text-muted">
    <div class="container">
        <p class="float-end">
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </p>
        <p>&copy; 2023 - Web</p>
    </div>
</footer>*@

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>


@*
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">АРМ администратора гостиницы</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Таблицы
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Apartaments" asp-action="Index">Апартаменты</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Bookings" asp-action="Index">Заказы</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Clients" asp-action="Index">Клиенты</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Facilities" asp-action="Index">Удобства</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Services" asp-action="Index">Услуги</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Tariffs" asp-action="Index">Тарифы</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>*@